--Unit Graphics weight = number of units * graphical factor * maintenance
NDefines.NMilitary.LIGHT_INFANTRY_GRAPHICAL_FACTOR = 2		-- 1.4
NDefines.NMilitary.HEAVY_INFANTRY_GRAPHICAL_FACTOR = 0.7	-- 2.1
NDefines.NMilitary.PIKEMEN_GRAPHICAL_FACTOR = 0.4			-- 2
NDefines.NMilitary.ARCHERS_GRAPHICAL_FACTOR = 1				-- 2
NDefines.NMilitary.LIGHT_CAVALRY_GRAPHICAL_FACTOR = 1		-- 3
NDefines.NMilitary.KNIGHTS_GRAPHICAL_FACTOR = 2.01			-- 12.06
NDefines.NMilitary.SPECIAL_TROOPS_GRAPHICAL_FACTOR = 0.25
NDefines.NCharacter.PORTRAIT_ADULT_MALE_AGE_THRESHOLD = 0
NDefines.NCharacter.PORTRAIT_ADULT_FEMALE_AGE_THRESHOLD = 0
