#!/bin/sh
./build

zip -r "Better Looking Garbs `date +%d%m%Y`.zip" betterlookinggarbs.mod betterlookinggarbs blgsubmods "Better Looking Garbs - Readme.txt" Changelog.txt betterlookinggarbs.jpg betterlookinggarbsinstall.exe betterlookinggarbsinstall.sh

mv ../betterlookinggarbs ../betterlookinggarbsfull
rm -rf ../betterlookinggarbsfull/gfx/fallbacks
cp -r blgsubmods ../betterlookinggarbsfull/submods
cp "Better Looking Garbs - Readme.txt" ../betterlookinggarbsfull
cp betterlookinggarbs.jpg ../betterlookinggarbsfull
cp Changelog.txt ../betterlookinggarbsfull

cp -r betterlookinggarbs ..
cp -r blgsubmods ../betterlookinggarbs/submods
cp "Better Looking Garbs - Readme.txt" ../betterlookinggarbs
cp betterlookinggarbs.jpg ../betterlookinggarbs
cp Changelog.txt ../betterlookinggarbs
cp betterlookinggarbsinstall.exe ../betterlookinggarbs
cp betterlookinggarbsinstall.sh ../betterlookinggarbs

cp -f workshop/* ..
