#!/bin/sh
rm ../betterlookinggarbs.mod
cp -f betterlookinggarbsfullupload.mod ../betterlookinggarbsfull.mod
cp betterlookinggarbs ../betterlookinggarbsfull
rm -rf ../betterlookinggarbsfull/gfx/fallbacks
rm ../betterlookinggarbsfull/betterlookinggarbsextra.zip
cp blgsubmods ../betterlookinggarbsfull/submods
cp "Better Looking Garbs - Readme.txt" ../betterlookinggarbsfull
cp betterlookinggarbs.jpg ../betterlookinggarbsfull
cp betterlookinggarbsfull.mod ../betterlookinggarbsfull
cp Changelog.txt ../betterlookinggarbsfull
